name: Test


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name : use Maven to build jar
        id: build
        run: mvn -B --file pom.xml test
      - name: Surefire Report
        if: success() || failure()
        uses: ScaCap/action-surefire-report@v1.7.0
